set surround
set ideavim-sneak
set multiple-cursors
set commentary
set argtextobj
set easymotion
set textobj-entire
set peekaboo
set functiontextobj
set ReplaceWithRegister
set exchange
set vim-paragraph-motion
set textobj-indent
set NERDTree
set which-key
Plug 'machakann/vim-highlightedyank'
