import = [
    "~/.config/alacritty/alacritty-theme/themes/hardhacker.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
opacity = 0.7
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"

[font]
normal.family = "Hack Nerd Font Mono"
offset = {y = 9, x = 1.2}
size = 17

[cursor]
style = {shape = "Beam", blinking = "Always"}
vi_mode_style = {shape = "Beam", blinking = "Always"}

[mouse]
hide_when_typing = true
