import = [
    "~/.config/alacritty/alacritty-theme/themes/cyber_punk_neon.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 5
opacity = 0.9
blur = true

startup_mode = "Maximized"
decorations = "None"

[font]
normal.family = "Hack Nerd Font Mono"
offset = {y = 10, x = 1}
size = 17

[cursor]
style = {shape = "Beam", blinking = "Always"}
vi_mode_style = {shape = "Beam", blinking = "Always"}

[mouse]
hide_when_typing = true
